### ISSUE TITLE
[Weekly report][Công Trình] Từ 17/4/2017 đến 22/4/2017

### ISSUE THREAD

**Issue by mcau2010** [phatls/FEEDBACKS#15]
Báo cáo tổng hợp:
1. Tổng kết từ ngày: 17/04/2017 - 22/04/2017
![image](https://cloud.githubusercontent.com/assets/18650658/25315093/d1f12848-2879-11e7-8695-f5c5fd911152.png)
2. SCHEDULE cho tuần tới từ ngày: 24/04/2017 - 28/04/2017
![image](https://cloud.githubusercontent.com/assets/18650658/25315096/e7ec91e6-2879-11e7-9a8e-2e4bf3992216.png)

Xem chi tiết: 
[Công trình dự án.xlsx](https://github.com/phatls/FEEDBACKS/files/949823/Cong.trinh.d.an.xlsx)

**Comment by phatls** [comment]
Weekly meeting 9h 24/04/2017
**_Thời gian họp:_**
Bắt đầu: 9h
Kết thúc: 11h
**_Thành phần tham dự:_**
PhatLS: Kiểm soát nội bộ; Án ngữ chăm sóc khách hàng 
Cầu: Phát triển kinh doanh; Án ngữ mua hàng 

**_Nội dung cuộc họp_**
# 1. Input/output Sale
PIC: Cầu
Status: Not yet
## Input 									
- dự án									
- nhà thầu chính							
- nhà thầu phụ							
- đối tác (chung KH, nhưng #sp)				
- Chủ đầu tư (chưa)

**Output**
Weekly report sale
- Dự án: Tiến độ; 4 đối tượng (nhà thầu chính; nhà thầu phụ; đối tác;  Chủ đầu tư)
- nhà thầu chính; nhà thầu phụ; đối tác: Keyword vật tự phụ; Project list;  Cơ hội bán hàng (báo giá)

# 2. Sourcing công trình: CM Công trình
PIC: Tuyển dụng mới
Status: Not yet

Thuế đầu vào
Sp mới
Tính sẵn sàng
Hậu mãi

# 3. Tuyển nhân viên kinh doanh
PIC: PhatLS
Status: Done

Chi tiết: 
https://github.com/phatls/FEEDBACKS/issues/16

# 4. Hỗ trợ phòng Mua hàng Bách Việt: 
PIC: Cầu
Status: Not yet

- Tách Detail design (hướng code), Function specification (hướng lập trình), Test case (optional)
- Cập nhật và bổ sung Input và output phòng mua hàng để release phối hợp phòng khác tiếp theo tuần 
- Quy định report phòng mua hàng (weekly report) là gì?
